#!/bin/bash

#SBATCH --job-name=intron_clustering
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=2:00:00
#SBATCH --mem=40G
#SBATCH  --output=/globalhome/hxo752/HPC/slurm_logs/%j.out

module load python/3.8.10

Rscript ~/envs/leafcutter/scripts/leafcutter_ds.R -o CTRLvsA1 --num_threads 4 -g 3 -i 3 -e ../../m10.exon.txt.gz ../junction/CTRLvsA1_perind_numers.counts.gz ../junction/groups_file.txt

../scripts/leafcutter_ds.R --num_threads 4 ../example_data/testYRIvsEU_perind_numers.counts.gz example_geuvadis/groups_file.txt
